apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: simple-jwt-api
  region: us-east-2
  version: "1.30"

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 2
    volumeSize: 20
    ssh:
      allow: false